# Site settings
title: Pearl Shin
email: pearlshin22@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pearlshin.github.io/" # the base hostname & protocol for your site
twitter_username: pearlsshin
github_username:  pearlshin

# Build settings
markdown: kramdown

# collections:
# - archives
